name: Publish Android

on: 
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/android.yml
    secrets: inherit

  publish:
    uses: starburst997/android-code-sign/.github/workflows/publish_android.yml@v1
    needs: [build]
    secrets: inherit
    with:
      lane: 'internal'