name: Release

# Create a simple release and save .apk in Github as well as publishing it in Google Play Console
on: 
  workflow_dispatch:
    inputs:
      notes:
        type: string
        description: Release Notes

jobs:
  version: # Get current version
    uses: starburst997/yearly-version/.github/workflows/version.yml@v1
    secrets: inherit

  version_increment: # Increment only if release is successful
    uses: starburst997/yearly-version/.github/workflows/version.yml@v1
    needs: [release]
    secrets: inherit
    with:
      increment: true

  build:
    uses: starburst997/android-code-sign/.github/workflows/android.yml@v1
    needs: [version]
    secrets: inherit
    with:
      path: 'android'
      module: 'app'
      version: ${{ needs.version.outputs.version }}

  publish:
    uses: starburst997/android-code-sign/.github/workflows/publish_android.yml@v1
    needs: [build]
    secrets: inherit
    with:
      lane: 'internal'
      keep-artifact: true

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [version, publish]
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
      
      - name: Tag release
        run: |
          git tag v${{ needs.version.outputs.version }}
          git push origin --tags

      - name: Generate Changelog
        if: ${{ inputs.notes != '' }}
        run: echo "${{ inputs.notes }}" > RELEASE.txt
        
      - name: Generate Changelog (empty)
        if: ${{ inputs.notes == '' }}
        run: echo "No notes" > RELEASE.txt

      - name: Download android artifact
        uses: actions/download-artifact@v4
        with:
          name: build-android
          path: build

      - name: Rename release
        working-directory: build
        run: |
          mv android.apk Test.apk

      - name: Release
        uses: starburst997/action-gh-release@v2
        with:
          body_path: RELEASE.txt
          token: ${{ secrets.GH_PAT }}
          tag_name: v${{ needs.version.outputs.version }}
          files: |
            build/Test.apk

      - name: Cleanup to avoid storage limit
        if: always()
        uses: starburst997/delete-artifact@v5
        with:
          name: build-android